### ISSUE TITLE
Округляйте до рублей

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/DepositService#2]
https://github.com/NailMukhametshin/DepositService/blob/d9b71b40d05ba022bbeddb99c3cf9f9bc47b5d52/src/test/java/ru/itpark/DepositTest.java#L12

**Comment by NailMukhametshin** [comment]
@coursar, исправил в 8c02c0a3b46d96d28dab98a44e4e80b4376b5fac
Изменил https://github.com/NailMukhametshin/DepositService/blob/8c02c0a3b46d96d28dab98a44e4e80b4376b5fac/src/main/java/ru/itpark/Deposit.java#L6
и получилось https://github.com/NailMukhametshin/DepositService/blob/8c02c0a3b46d96d28dab98a44e4e80b4376b5fac/src/test/java/ru/itpark/DepositTest.java#L11-L15
