### ISSUE TITLE
Заменить Qualified Name на import

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/DepositService#3]
https://github.com/NailMukhametshin/DepositService/blob/d9b71b40d05ba022bbeddb99c3cf9f9bc47b5d52/src/test/java/ru/itpark/DepositTest.java#L7

Должно быть <pre>@Test</pre>

**Comment by NailMukhametshin** [comment]
@coursar, исправил в 8c02c0a3b46d96d28dab98a44e4e80b4376b5fac
https://github.com/NailMukhametshin/DepositService/blob/8c02c0a3b46d96d28dab98a44e4e80b4376b5fac/src/test/java/ru/itpark/DepositTest.java#L3-L9

**Comment by coursar** [comment]
@NailMukhametshin, не делайте одним коммитом не связанных друг с другом изменений
